#include "Couteau.h"
#include <iostream>
using namespace std; 



void Couteau::Afficher()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33-46c6bf1a:13b99db6061:-8000:0000000000000C1E begin
{
	cout << "Arme : " <<  Arme::m_NomComplet  << " Degats  : "  << Arme::m_degats << endl;    
}
// section -64--88-1-33-46c6bf1a:13b99db6061:-8000:0000000000000C1E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Couteau::Couteau(string Qualifiant, int Degats)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33-46c6bf1a:13b99db6061:-8000:0000000000000C24 begin
{
	m_GenreArme = "Couteau ";
    m_NomQualifiant =  Qualifiant;
	// On initialise les  membres de Arme
	m_degats = Degats; 
	m_NomComplet = m_GenreArme +  m_NomQualifiant;
}
// section -64--88-1-33-46c6bf1a:13b99db6061:-8000:0000000000000C24 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Couteau::Couteau()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-33-46c6bf1a:13b99db6061:-8000:0000000000000C5F begin
{
}
// section -64--88-1-33-46c6bf1a:13b99db6061:-8000:0000000000000C5F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Couteau::~Couteau()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-37843895:13ba5147594:-8000:0000000000000B5A begin
{
}
// section -64--88-1-58-37843895:13ba5147594:-8000:0000000000000B5A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Couteau::Frapper()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-37843895:13ba5147594:-8000:0000000000000B64 begin
{
    cout << "Coup de Couteau " << m_NomQualifiant << endl;
	return m_degats;
	
}
// section -64--88-1-58-37843895:13ba5147594:-8000:0000000000000B64 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Couteau::Planter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-58-37843895:13ba5147594:-8000:0000000000000B66 begin
{
    return 0;
}
// section -64--88-1-58-37843895:13ba5147594:-8000:0000000000000B66 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
